### PR TITLE
Adds a file with questions for the mentors to ask

### PR DESCRIPTION
**Pull request by lucymonie**

### CODE REVIEW

**Comment by lucymonie** [comment]
Hey @skibinska I feel worried that we don't have consensus on what to do with this given we have to deliver it tomorrow. I would love your feedback.

@Jbarget - would love your thoughts on what works with this too. How did it go?

**Comment by lucymonie** [comment]
@emilyb7 I would love to know your thoughts about the questions to ask after each readme. There's some concern that it will take too long for the time that we have allowed. This is discussed in #2. Any thoughts?

**Comment by emilyb7** [comment]
yeah, I've seen the discussion and understand the concerns. I would suggest that we play it by ear tomorrow. Better to be overprepared than not have enough to do!

**Comment by skibinska** [comment]
Sorry @lucymonie for late response. I wrote [here](https://github.com/lucymonie/api-workshop/issues/2#issuecomment-284225504) what I think we could do :)

**Comment by Jbarget** [comment]
i left our experience in #2, if theres anything specific you want to know let me know :)

**Comment by lucymonie** [comment]
Thanks all, that's really helpful. Seems like seeing how much time we have is the best approach.

**Comment by Jbarget** [comment]
@lucymonie was there consensus on this? how did it go down for you? did you get through everything?

**Comment by lucymonie** [comment]
Good point! We used your example and somewhat skipped the Asynchronous readme. However, it cam up in a question someone asked, so we watched the loupe example to demonstrate how asynchronous code works in the js run time. 

We asked the following questions

Request and response:
- Ask two people from the cohort to stand up and draw the request-response pattern on the whiteboard and explain what happens
- What is the request property responseText?
- What JSON method can we use to transform a responseText string into something we can use?

HTTP
- What is HTTP?
- Name three HTTP methods.
(They asked about the difference between PUT and POST)

XMLHttpRequest
- How do you create a new XHR object?
- Why do we check on the onreadystatechange property?

**Comment by Jbarget** [comment]
I wouldn't have felt comfortable asking members of the cohort to stand up and draw the cycle, I think mainly due to the fact that giving local students 10/15 mins to read and understand large chunks of English

**Comment by Jbarget** [comment]
@lucymonie where do we stand on this?

**Comment by eliascodes** [comment]
This file now exists: https://github.com/foundersandcoders/api-workshop/blob/master/mentor-notes.md

Closing.

**Pull request closed without merging**
